# permissions for end users to view shareintents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shareintent-viewer-role
rules:
- apiGroups:
  - share.phillebaba.io
  resources:
  - shareintents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - share.phillebaba.io
  resources:
  - shareintents/status
  verbs:
  - get
